
package com.hoau.crm.module.sales.server.si.oa;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-07-01T09:49:15.166+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class OaSaleServicePortType_OaSaleServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("OaSaleService", "OaSaleService");

    private OaSaleServicePortType_OaSaleServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OaSaleService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OaSaleService ss = new OaSaleService(wsdlURL, SERVICE_NAME);
        OaSaleServicePortType port = ss.getOaSaleServiceHttpPort();  
        
        {
        System.out.println("Invoking getSalInfo...");
        java.lang.String _getSalInfo_in0 = "";
        java.lang.String _getSalInfo__return = port.getSalInfo(_getSalInfo_in0);
        System.out.println("getSalInfo.result=" + _getSalInfo__return);


        }

        System.exit(0);
    }

}
