
package com.hoau.crm.module.sales.server.si.oa;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-07-01T09:49:15.202+08:00
 * Generated source version: 2.7.14
 * 
 */
 
public class OaSaleServicePortType_OaSaleServiceHttpPort_Server{

    protected OaSaleServicePortType_OaSaleServiceHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OaSaleServicePortTypeImpl();
        String address = "http://10.39.251.142/services/OaSaleService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OaSaleServicePortType_OaSaleServiceHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
