package com.hoau.crm.module.sales.server.si.oa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-07-01T09:49:15.206+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "OaSaleService", 
                  wsdlLocation = "http://10.39.251.142/services/OaSaleService?wsdl",
                  targetNamespace = "OaSaleService") 
public class OaSaleService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("OaSaleService", "OaSaleService");
    public final static QName OaSaleServiceHttpPort = new QName("OaSaleService", "OaSaleServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.251.142/services/OaSaleService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OaSaleService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.251.142/services/OaSaleService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OaSaleService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OaSaleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OaSaleService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OaSaleServicePortType
     */
    @WebEndpoint(name = "OaSaleServiceHttpPort")
    public OaSaleServicePortType getOaSaleServiceHttpPort() {
        return super.getPort(OaSaleServiceHttpPort, OaSaleServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OaSaleServicePortType
     */
    @WebEndpoint(name = "OaSaleServiceHttpPort")
    public OaSaleServicePortType getOaSaleServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(OaSaleServiceHttpPort, OaSaleServicePortType.class, features);
    }

}
