
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.crm.module.sales.server.si.oa;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-07-01T09:49:15.185+08:00
 * Generated source version: 2.7.14
 * 
 */

@javax.jws.WebService(
                      serviceName = "OaSaleService",
                      portName = "OaSaleServiceHttpPort",
                      targetNamespace = "OaSaleService",
                      wsdlLocation = "http://10.39.251.142/services/OaSaleService?wsdl",
                      endpointInterface = "com.hoau.crm.module.sales.server.si.oa.OaSaleServicePortType")
                      
public class OaSaleServicePortTypeImpl implements OaSaleServicePortType {

    private static final Logger LOG = Logger.getLogger(OaSaleServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.crm.module.sales.server.si.oa.OaSaleServicePortType#getSalInfo(java.lang.String  in0 )*
     */
    public java.lang.String getSalInfo(java.lang.String in0) { 
        LOG.info("Executing operation getSalInfo");
        System.out.println(in0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
