
package com.hoau.crm.module.customer.server.si.dc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2016-01-07T10:47:14.377+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class CRMServices_CRMServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.hoau.net/services/CRMServices", "CRMServices");

    private CRMServices_CRMServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CRMServices_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CRMServices_Service ss = new CRMServices_Service(wsdlURL, SERVICE_NAME);
        CRMServices port = ss.getCRMServicesPort();  
        
        {
        System.out.println("Invoking addCustomer...");
        com.hoau.crm.module.customer.server.si.dc.CrmCustomer _addCustomer_customer = null;
        com.hoau.crm.module.customer.server.si.dc.ResultMsg _addCustomer__return = port.addCustomer(_addCustomer_customer);
        System.out.println("addCustomer.result=" + _addCustomer__return);


        }
        {
        System.out.println("Invoking modifyCustomer...");
        com.hoau.crm.module.customer.server.si.dc.CrmCustomer _modifyCustomer_customer = null;
        com.hoau.crm.module.customer.server.si.dc.ResultMsg _modifyCustomer__return = port.modifyCustomer(_modifyCustomer_customer);
        System.out.println("modifyCustomer.result=" + _modifyCustomer__return);


        }
        {
        System.out.println("Invoking deleteCustomer...");
        com.hoau.crm.module.customer.server.si.dc.CrmCustomer _deleteCustomer_customer = null;
        com.hoau.crm.module.customer.server.si.dc.ResultMsg _deleteCustomer__return = port.deleteCustomer(_deleteCustomer_customer);
        System.out.println("deleteCustomer.result=" + _deleteCustomer__return);


        }

        System.exit(0);
    }

}
