
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.crm.module.customer.server.si.dc;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2016-01-07T10:47:14.398+08:00
 * Generated source version: 2.7.14
 * 
 */

@javax.jws.WebService(
                      serviceName = "CRMServices",
                      portName = "CRMServicesPort",
                      targetNamespace = "http://www.hoau.net/services/CRMServices",
                      wsdlLocation = "http://10.39.109.29:8080/services/CRMServices?wsdl",
                      endpointInterface = "com.hoau.crm.module.customer.server.si.dc.CRMServices")
                      
public class CRMServicesImpl implements CRMServices {

    private static final Logger LOG = Logger.getLogger(CRMServicesImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.crm.module.customer.server.si.dc.CRMServices#addCustomer(com.hoau.crm.module.customer.server.si.dc.CrmCustomer  customer )*
     */
    public com.hoau.crm.module.customer.server.si.dc.ResultMsg addCustomer(com.hoau.crm.module.customer.server.si.dc.CrmCustomer customer) { 
        LOG.info("Executing operation addCustomer");
        System.out.println(customer);
        try {
            com.hoau.crm.module.customer.server.si.dc.ResultMsg _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.crm.module.customer.server.si.dc.CRMServices#modifyCustomer(com.hoau.crm.module.customer.server.si.dc.CrmCustomer  customer )*
     */
    public com.hoau.crm.module.customer.server.si.dc.ResultMsg modifyCustomer(com.hoau.crm.module.customer.server.si.dc.CrmCustomer customer) { 
        LOG.info("Executing operation modifyCustomer");
        System.out.println(customer);
        try {
            com.hoau.crm.module.customer.server.si.dc.ResultMsg _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.crm.module.customer.server.si.dc.CRMServices#deleteCustomer(com.hoau.crm.module.customer.server.si.dc.CrmCustomer  customer )*
     */
    public com.hoau.crm.module.customer.server.si.dc.ResultMsg deleteCustomer(com.hoau.crm.module.customer.server.si.dc.CrmCustomer customer) { 
        LOG.info("Executing operation deleteCustomer");
        System.out.println(customer);
        try {
            com.hoau.crm.module.customer.server.si.dc.ResultMsg _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
