
package com.hoau.crm.module.customer.server.si.dc;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2016-01-07T10:47:14.419+08:00
 * Generated source version: 2.7.14
 * 
 */
 
public class CRMServices_CRMServicesPort_Server{

    protected CRMServices_CRMServicesPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CRMServicesImpl();
        String address = "http://10.39.109.29:8080/services/CRMServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CRMServices_CRMServicesPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
