
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.crm.module.job.server.wsdl.oa;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-06-05T14:42:49.054+08:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrgEmpService",
                      portName = "OrgEmpServiceHttpPort",
                      targetNamespace = "OrgEmpService",
                      wsdlLocation = "http://10.39.251.142//services/OrgEmpService?wsdl",
                      endpointInterface = "com.hoau.crm.module.job.server.wsdl.oa.OrgEmpServicePortType")
                      
public class OrgEmpServicePortTypeImpl implements OrgEmpServicePortType {

    private static final Logger LOG = Logger.getLogger(OrgEmpServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.crm.module.job.server.wsdl.oa.OrgEmpServicePortType#getEmp(java.lang.String  in0 ,)java.lang.String  in1 )*
     */
    public java.lang.String getEmp(java.lang.String in0,java.lang.String in1) { 
        LOG.info("Executing operation getEmp");
        System.out.println(in0);
        System.out.println(in1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.crm.module.job.server.wsdl.oa.OrgEmpServicePortType#getJob(java.lang.String  in0 ,)java.lang.String  in1 )*
     */
    public java.lang.String getJob(java.lang.String in0,java.lang.String in1) { 
        LOG.info("Executing operation getJob");
        System.out.println(in0);
        System.out.println(in1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.crm.module.job.server.wsdl.oa.OrgEmpServicePortType#getOrg(java.lang.String  in0 ,)java.lang.String  in1 )*
     */
    public java.lang.String getOrg(java.lang.String in0,java.lang.String in1) { 
        LOG.info("Executing operation getOrg");
        System.out.println(in0);
        System.out.println(in1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
