package com.hoau.crm.module.job.server.wsdl.oa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-06-05T14:42:49.066+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "OrgEmpService", name = "OrgEmpServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface OrgEmpServicePortType {

    @WebResult(name = "out", targetNamespace = "OrgEmpService")
    @RequestWrapper(localName = "getEmp", targetNamespace = "OrgEmpService", className = "com.hoau.crm.module.job.server.wsdl.oa.GetEmp")
    @WebMethod
    @ResponseWrapper(localName = "getEmpResponse", targetNamespace = "OrgEmpService", className = "com.hoau.crm.module.job.server.wsdl.oa.GetEmpResponse")
    public java.lang.String getEmp(
        @WebParam(name = "in0", targetNamespace = "OrgEmpService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "OrgEmpService")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "OrgEmpService")
    @RequestWrapper(localName = "getJob", targetNamespace = "OrgEmpService", className = "com.hoau.crm.module.job.server.wsdl.oa.GetJob")
    @WebMethod
    @ResponseWrapper(localName = "getJobResponse", targetNamespace = "OrgEmpService", className = "com.hoau.crm.module.job.server.wsdl.oa.GetJobResponse")
    public java.lang.String getJob(
        @WebParam(name = "in0", targetNamespace = "OrgEmpService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "OrgEmpService")
        java.lang.String in1
    );

    @WebResult(name = "out", targetNamespace = "OrgEmpService")
    @RequestWrapper(localName = "getOrg", targetNamespace = "OrgEmpService", className = "com.hoau.crm.module.job.server.wsdl.oa.GetOrg")
    @WebMethod
    @ResponseWrapper(localName = "getOrgResponse", targetNamespace = "OrgEmpService", className = "com.hoau.crm.module.job.server.wsdl.oa.GetOrgResponse")
    public java.lang.String getOrg(
        @WebParam(name = "in0", targetNamespace = "OrgEmpService")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "OrgEmpService")
        java.lang.String in1
    );
}
