package com.hoau.crm.module.job.server.wsdl.oa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-06-05T14:42:49.078+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "OrgEmpService", 
                  wsdlLocation = "http://10.39.251.142//services/OrgEmpService?wsdl",
                  targetNamespace = "OrgEmpService") 
public class OrgEmpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("OrgEmpService", "OrgEmpService");
    public final static QName OrgEmpServiceHttpPort = new QName("OrgEmpService", "OrgEmpServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.251.142//services/OrgEmpService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrgEmpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.251.142//services/OrgEmpService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrgEmpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrgEmpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrgEmpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OrgEmpServicePortType
     */
    @WebEndpoint(name = "OrgEmpServiceHttpPort")
    public OrgEmpServicePortType getOrgEmpServiceHttpPort() {
        return super.getPort(OrgEmpServiceHttpPort, OrgEmpServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrgEmpServicePortType
     */
    @WebEndpoint(name = "OrgEmpServiceHttpPort")
    public OrgEmpServicePortType getOrgEmpServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(OrgEmpServiceHttpPort, OrgEmpServicePortType.class, features);
    }

}
