
package com.hoau.crm.module.job.server.wsdl.oa;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-06-05T14:42:49.019+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class OrgEmpServicePortType_OrgEmpServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("OrgEmpService", "OrgEmpService");

    private OrgEmpServicePortType_OrgEmpServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrgEmpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrgEmpService ss = new OrgEmpService(wsdlURL, SERVICE_NAME);
        OrgEmpServicePortType port = ss.getOrgEmpServiceHttpPort();  
        
        {
        System.out.println("Invoking getEmp...");
        java.lang.String _getEmp_in0 = "";
        java.lang.String _getEmp_in1 = "";
        java.lang.String _getEmp__return = port.getEmp(_getEmp_in0, _getEmp_in1);
        System.out.println("getEmp.result=" + _getEmp__return);


        }
        {
        System.out.println("Invoking getJob...");
        java.lang.String _getJob_in0 = "";
        java.lang.String _getJob_in1 = "";
        java.lang.String _getJob__return = port.getJob(_getJob_in0, _getJob_in1);
        System.out.println("getJob.result=" + _getJob__return);


        }
        {
        System.out.println("Invoking getOrg...");
        java.lang.String _getOrg_in0 = "";
        java.lang.String _getOrg_in1 = "";
        java.lang.String _getOrg__return = port.getOrg(_getOrg_in0, _getOrg_in1);
        System.out.println("getOrg.result=" + _getOrg__return);


        }

        System.exit(0);
    }

}
