package com.hoau.crm.module.common.server.wsdl.obh;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-12-29T09:11:15.208+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://service.server.crm.module.obh.hoau.com/", name = "ISyncFacadeService")
@XmlSeeAlso({ObjectFactory.class})
public interface ISyncFacadeService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateShipperInfo", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.UpdateShipperInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateShipperInfoResponse", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.UpdateShipperInfoResponse")
    public com.hoau.crm.module.common.server.wsdl.obh.ResResult updateShipperInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateSyncSuccessInfo", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.UpdateSyncSuccessInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateSyncSuccessInfoResponse", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.UpdateSyncSuccessInfoResponse")
    public com.hoau.crm.module.common.server.wsdl.obh.ResResult updateSyncSuccessInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateUserInfo", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.UpdateUserInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateUserInfoResponse", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.UpdateUserInfoResponse")
    public com.hoau.crm.module.common.server.wsdl.obh.ResResult updateUserInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryNotSyncInfos", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.QueryNotSyncInfos")
    @WebMethod
    @ResponseWrapper(localName = "queryNotSyncInfosResponse", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.QueryNotSyncInfosResponse")
    public com.hoau.crm.module.common.server.wsdl.obh.ResResult queryNotSyncInfos(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.RegisterUser")
    @WebMethod
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://service.server.crm.module.obh.hoau.com/", className = "com.hoau.crm.module.common.server.wsdl.obh.RegisterUserResponse")
    public com.hoau.crm.module.common.server.wsdl.obh.RegisterUserResModel registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
