/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.crm.module.common.server.wsdl.obh;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-12-29T09:11:15.186+08:00
 * Generated source version: 2.7.14
 * 
 */

@javax.jws.WebService(
                      serviceName = "SyncService",
                      portName = "SyncFacadeServiceImplPort",
                      targetNamespace = "http://service.server.crm.module.obh.hoau.com/",
                      wsdlLocation = "http://10.39.117.92:8080/obh-web/services/SyncService?wsdl",
                      endpointInterface = "com.hoau.crm.module.common.server.wsdl.obh.ISyncFacadeService")
                      
public class ISyncFacadeServiceImpl implements ISyncFacadeService {

    private static final Logger LOG = Logger.getLogger(ISyncFacadeServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.crm.module.common.server.wsdl.obh.ISyncFacadeService#updateShipperInfo(java.lang.String  arg0 )*
     */
    public com.hoau.crm.module.common.server.wsdl.obh.ResResult updateShipperInfo(java.lang.String arg0) { 
        LOG.info("Executing operation updateShipperInfo");
        System.out.println(arg0);
        try {
            com.hoau.crm.module.common.server.wsdl.obh.ResResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.crm.module.common.server.wsdl.obh.ISyncFacadeService#updateSyncSuccessInfo(java.lang.String  arg0 ,)java.lang.String  arg1 )*
     */
    public com.hoau.crm.module.common.server.wsdl.obh.ResResult updateSyncSuccessInfo(java.lang.String arg0,java.lang.String arg1) { 
        LOG.info("Executing operation updateSyncSuccessInfo");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            com.hoau.crm.module.common.server.wsdl.obh.ResResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.crm.module.common.server.wsdl.obh.ISyncFacadeService#updateUserInfo(java.lang.String  arg0 )*
     */
    public com.hoau.crm.module.common.server.wsdl.obh.ResResult updateUserInfo(java.lang.String arg0) { 
        LOG.info("Executing operation updateUserInfo");
        System.out.println(arg0);
        try {
            com.hoau.crm.module.common.server.wsdl.obh.ResResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.crm.module.common.server.wsdl.obh.ISyncFacadeService#queryNotSyncInfos(java.lang.String  arg0 )*
     */
    public com.hoau.crm.module.common.server.wsdl.obh.ResResult queryNotSyncInfos(java.lang.String arg0) { 
        LOG.info("Executing operation queryNotSyncInfos");
        System.out.println(arg0);
        try {
            com.hoau.crm.module.common.server.wsdl.obh.ResResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.crm.module.common.server.wsdl.obh.ISyncFacadeService#registerUser(java.lang.String  arg0 )*
     */
    public com.hoau.crm.module.common.server.wsdl.obh.RegisterUserResModel registerUser(java.lang.String arg0) { 
        LOG.info("Executing operation registerUser");
        System.out.println(arg0);
        try {
            com.hoau.crm.module.common.server.wsdl.obh.RegisterUserResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
