package com.hoau.crm.module.common.server.wsdl.obh;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-12-29T09:11:15.166+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class ISyncFacadeService_SyncFacadeServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.server.crm.module.obh.hoau.com/", "SyncService");

    private ISyncFacadeService_SyncFacadeServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SyncService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SyncService ss = new SyncService(wsdlURL, SERVICE_NAME);
        ISyncFacadeService port = ss.getSyncFacadeServiceImplPort();  
        
        {
        System.out.println("Invoking updateShipperInfo...");
        java.lang.String _updateShipperInfo_arg0 = "";
        com.hoau.crm.module.common.server.wsdl.obh.ResResult _updateShipperInfo__return = port.updateShipperInfo(_updateShipperInfo_arg0);
        System.out.println("updateShipperInfo.result=" + _updateShipperInfo__return);


        }
        {
        System.out.println("Invoking updateSyncSuccessInfo...");
        java.lang.String _updateSyncSuccessInfo_arg0 = "";
        java.lang.String _updateSyncSuccessInfo_arg1 = "";
        com.hoau.crm.module.common.server.wsdl.obh.ResResult _updateSyncSuccessInfo__return = port.updateSyncSuccessInfo(_updateSyncSuccessInfo_arg0, _updateSyncSuccessInfo_arg1);
        System.out.println("updateSyncSuccessInfo.result=" + _updateSyncSuccessInfo__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_arg0 = "";
        com.hoau.crm.module.common.server.wsdl.obh.ResResult _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_arg0);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking queryNotSyncInfos...");
        java.lang.String _queryNotSyncInfos_arg0 = "";
        com.hoau.crm.module.common.server.wsdl.obh.ResResult _queryNotSyncInfos__return = port.queryNotSyncInfos(_queryNotSyncInfos_arg0);
        System.out.println("queryNotSyncInfos.result=" + _queryNotSyncInfos__return);


        }
        {
        System.out.println("Invoking registerUser...");
        java.lang.String _registerUser_arg0 = "";
        com.hoau.crm.module.common.server.wsdl.obh.RegisterUserResModel _registerUser__return = port.registerUser(_registerUser_arg0);
        System.out.println("registerUser.result=" + _registerUser__return);


        }

        System.exit(0);
    }

}
