package com.hoau.crm.module.common.server.wsdl.obh;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-12-29T09:11:15.216+08:00
 * Generated source version: 2.7.14
 * 
 */
 
public class ISyncFacadeService_SyncFacadeServiceImplPort_Server{

    protected ISyncFacadeService_SyncFacadeServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ISyncFacadeServiceImpl();
        String address = "http://10.39.117.92:8080/obh-web/services/SyncService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ISyncFacadeService_SyncFacadeServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
