package com.hoau.crm.module.common.server.wsdl.obh;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-12-29T09:11:15.219+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "SyncService", 
                  wsdlLocation = "http://10.39.117.92:8080/obh-web/services/SyncService?wsdl",
                  targetNamespace = "http://service.server.crm.module.obh.hoau.com/") 
public class SyncService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.server.crm.module.obh.hoau.com/", "SyncService");
    public final static QName SyncFacadeServiceImplPort = new QName("http://service.server.crm.module.obh.hoau.com/", "SyncFacadeServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.117.92:8080/obh-web/services/SyncService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SyncService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.117.92:8080/obh-web/services/SyncService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SyncService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ISyncFacadeService
     */
    @WebEndpoint(name = "SyncFacadeServiceImplPort")
    public ISyncFacadeService getSyncFacadeServiceImplPort() {
        return super.getPort(SyncFacadeServiceImplPort, ISyncFacadeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISyncFacadeService
     */
    @WebEndpoint(name = "SyncFacadeServiceImplPort")
    public ISyncFacadeService getSyncFacadeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SyncFacadeServiceImplPort, ISyncFacadeService.class, features);
    }

}
